# Generated by Django 4.2.6 on 2024-03-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInfo',
            new_name='StockInfo44',
        ),
    ]
