# Generated by Django 4.2.6 on 2024-03-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_stockinfo_stockinfo44'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInfo44',
            new_name='StockInfo',
        ),
    ]
