# Generated by Django 5.0.2 on 2024-03-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_stockinfo44_stockinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInfo',
            new_name='StockInfotable',
        ),
    ]
